# name: CD

# on:
#   push:
#     branches:
#       - "*"

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Print Docker Username (Optional for Debugging)
#         run: echo ${{ secrets.DOCKER_USERNAME }}

#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Login to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ secrets.DOCKER_USERNAME }}
#           password: ${{ secrets.DOCKER_PASSWORD }}

#       - name: Build Docker image
#         run: docker build -t ${{ secrets.DOCKER_USERNAME }}/app-helm:${{ github.sha }} .

#       - name: Push Docker image
#         run: docker push ${{ secrets.DOCKER_USERNAME }}/app-helm:${{ github.sha }}

#       - name: Update values.yaml
#         run: |
#           cd helm
#           sed -i 's|APP_VERSION:.*|APP_VERSION: '${{ github.sha }}'|' values.yaml 
#           git config --global user.name 'GitHub Actions'
#           git config --global user.email 'actions@github.com'
#           git add values.yaml
#           git commit -m "Update values.yaml"
#           git push


name: Auto Label Issues

on:
  issues:
    types: [opened]

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
    - name: Add label using GitHub API
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        curl -X POST \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
          -d '{"labels": ["new issue"]}'
